name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Check Committer
        id: check-committer
        run: echo "::set-output name=is_committer::$(if [ "$(git log -1 --pretty=%B)" == 'Generate Doxygen documentation' ]; then echo false; else echo true; fi)"

      - name: Commit and Push Documentation
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add path/to/your/generated/docs
          git commit -m "Generate Doxygen documentation"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

