name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Check Committer
        id: check-committer
        run: echo "::set-output name=is_committer::$(if [ "$(git log -1 --pretty=%B)" == 'Generate Doxygen documentation' ]; then echo false; else echo true; fi)"

      - name: Commit Documentation
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://${{ github.actor }}:$GITHUB_TOKEN@github.com/${{ github.repository }}
          mkdir testFolder
          git add testFolder
          git status
          git commit -m "Generate Doxygen documentation"


      - name: Check for Changes
        id: check-changes
        run: echo "::set-output name=has_changes::$(git status --porcelain)"

      - name: Push Documentation
        if: steps.check-changes.outputs.has_changes != ''
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
