name: install doxygen

on: workflow_dispatch

jobs:
  generate-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Install Doxygen
        run: |
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_8/doxygen-1.9.8.linux.bin.tar.gz
          tar -xzvf doxygen-1.9.8.linux.bin.tar.gz

          cd doxygen-1.9.8
          sudo make install

      - name: PRINT Doxygen VERSION
        run: doxygen -v

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODIFIED: ${{ env.MODIFIED }}
          LAST_COMMIT_IS_DOCUMENTATION: ${{ env.LAST_COMMIT_IS_DOCUMENTATION }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
